### ISSUE TITLE
Composite Proceeding.py error MaskHandler

### ISSUE THREAD

**Issue by WOTR-VJ** [Sen2Agri/Sen2Agri-System#15]
I am running the composite processing in manual mode for single time series S2 tile.
I am getting the following error.

ERROR: No value associated to the parameter : “xml”, invalid number of values 0
ERROR: Troubles loading parameter, please check your line argument…

Any idea where it went wrong?

**Comment by lnicola** [comment]
Hi, can you paste your command line here? You can leave out the input products if you prefer.

**Comment by WOTR-VJ** [comment]
Hi Laurențiu Nicola,

I have attached the command line. Please let me know if you need further
information.
Thanks
Vijay

**Comment by lnicola** [comment]
@WOTR-VJ If you attached it when replying to the GitHub notification mail, it doesn't seem to work. You'll have to paste it in the comment for, preferably between ``` lines.

**Comment by WOTR-VJ** [comment]
Hi Laurențiu Nicola,

I have attached the command line. Please let me know if you need further
information.
"
[image: L3A_error (1).jpg]
"
Thanks
Vijay

**Comment by lnicola** [comment]
Hi Vijay,

That didn't work either. Can you paste it as text?

**Comment by WOTR-VJ** [comment]
Okay. Let me try one more time
![l3a_error](https://user-images.githubusercontent.com/29091748/48314058-15769100-e5ea-11e8-9a71-1b44c31883c4.jpg)
Vijay

**Comment by lnicola** [comment]
So the input products need to be L2As as created by MACCS. Are you running some `composite.py` script? What aguments are you passing it?

**Comment by WOTR-VJ** [comment]
Yes, I have used the outputs from MACCS. But I have used composite_processing.py
The arguments are
./composite_processing.py --syntdate 20181002 --synthalf 25 --input \ "/mnt/archive/temp/maccs_temp/S2A_MSIL2A_20180902T052641_N0206_R105_T43QDB_20180902T085243.SAFE/S2A_OPER_SSC_L2VALD_43QDB____20180902.HDR" \ "/mnt/archive/temp/maccs_temp/S2A_MSIL2A_20180912T052641_N0206_R105_T43QDB_20180912T092003.SAFE/S2A_OPER_SSC_L2VALD_43QDB____20180912.HDR" \ "/mnt/archive/temp/maccs_temp/S2A_MSIL2A_20181002T052641_N0206_R105_T43QDB_20181002T084928.SAFE/S2A_OPER_SSC_L2VALD_43QDB____20181002.HDR" \ "/mnt/archive/temp/maccs_temp/S2B_MSIL2A_20181007T052709_N0206_R105_T43QDB_20181007T091700.SAFE/S2B_OPER_SSC_L2VALD_43QDB____20181007.HDR" \ "/mnt/archive/temp/maccs_temp/S2A_MSIL2A_20181012T052741_N0206_R105_T43QDB_20181012T082210.SAFE/S2A_OPER_SSC_L2VALD_43QDB____20181012.HDR" \  --res 10 --outdir "/mnt/archive/temp/20181002/43QDB" --bandsmap /usr/share/sen2agri/composite/bands_mapping_s2_L8.txt --scatteringcoef /usr/share/sen2agri/composite/scattering_coeffs_10m.txt

**Comment by WOTR-VJ** [comment]
Okay, I remove \ in the argument and try to re-run the process. Based on my system configuration it may take almost 5 hours. I send you the update.
thanks
VJ

**Comment by WOTR-VJ** [comment]
Hi@lnicola
The code completed successfully and TILE ID folder created with one composite. 
However, only 10m bands (4 bands) are created. How about other bands 20m and 60m?

**Comment by lnicola** [comment]
You can produce the 20m composite by replacing `--res 10` with `--res 20` in the command line. MACCS does not output the 60m bands.

**Comment by WOTR-VJ** [comment]
But for LAI and Pheno processing why the L2A output is being used (Sen2-Agri Manual) instead of L3A output. Could you please explain that.

**Comment by lnicola** [comment]
That's true, and it's by design. I wasn't personally involved in the design of those processors, but I assume that avoiding the smoothing of the inputs and not having to wait 25 days for the output were deemed to be more important than having some output data for the cloudy pixels.

**Comment by WOTR-VJ** [comment]
So it is possible to use the L3A output for the L3B processing and crop mapping?
Or I should only use L2A products

**Comment by lnicola** [comment]
The L4 processors do their own gap-filling for cloudy pixels. L3As are not used as inputs, and wouldn't work without changing the processors.

**Comment by lnicola** [comment]
There should be the ATBDs (the algorithm descriptions) which describe the individual processors in more detail. I don't think they are available on the project site right now, but I can ask around to see whether it's possible to publish them.

**Comment by WOTR-VJ** [comment]
Okay thank you
