### ISSUE TITLE
Missing S2 tile in L4A classification

### ISSUE THREAD

**Issue by valpesendorfer** [Sen2Agri/Sen2Agri-System#21]
Hi,

I've noticed that in our cropmask, one entire S2 tile seems to be missing in the classification. You can clearly tell, because there's a sharp cut in the classified area of the adjacent tile. There's no pixel classified as crop in this specific tile (I've checked that programmatically, not only visually), even though there's insitu-data present. Is there any way to check why that happens and how I can fix it?

Here's some additional info:

S2 tile-id: **35NRH**

Screenshot with classification and S2 tiling grid overlayed (white pixels == crop, yellow dots == crop reference, red == non-crop)

![screenshot](https://user-images.githubusercontent.com/18698817/57138492-16c39200-6db3-11e9-983d-c23c67a4573f.png)

Here's the _MCMFLG_ for the tile 35 NRH:

![MCMFLG](https://user-images.githubusercontent.com/18698817/57138766-d7e20c00-6db3-11e9-9d98-8a38fa8a3835.png)

And just a random _mosaic.jpg_ out of 70:
![S2A_MSIL2A_20180314T080711_N0206_R078_T35NRH_20180314T101113 SAFE-mosaic](https://user-images.githubusercontent.com/18698817/57138637-7b7eec80-6db3-11e9-8084-f9f8a11caeed.jpg)

Thanks!

**Comment by lnicola** [comment]
It's not very clear from the screenshots, but we noticed some S2 tiles where the density of the acquisitions is much worse than on the neighboring ones. Can you compare the flags for `35NRH` and its neighbors?

**Comment by valpesendorfer** [comment]
It looks like the density is lower - but given that there _is_ both S2 and in-situ data - shouldn't there also be classified pixels?

Here's two screenshots comparing the flags:

![image](https://user-images.githubusercontent.com/18698817/57219936-e91c5a00-6ff9-11e9-880a-729e3fd584c7.png)

and without `35NRH`:

![image](https://user-images.githubusercontent.com/18698817/57219966-018c7480-6ffa-11e9-8689-8e8f4186ec21.png)

**Comment by lnicola** [comment]
Can you check the values? There might be some scaling involved to fit the histogram of the image.

**Comment by valpesendorfer** [comment]
I'm not familiar with the actual info contained in the flag images, so I'll just post the histograms:

`35NRH`:

![image](https://user-images.githubusercontent.com/18698817/57220301-1cabb400-6ffb-11e9-8811-a4b215b35245.png)

`35NQH`:

![image](https://user-images.githubusercontent.com/18698817/57220337-3947ec00-6ffb-11e9-8d84-319233b54d50.png)

`36NTN`:

![image](https://user-images.githubusercontent.com/18698817/57220359-541a6080-6ffb-11e9-880c-08101cb199b4.png)

**Comment by lnicola** [comment]
The four bands should be:

 - the number of valid pixels across the time series
 - the number of water pixels across the time series
 - the number of snow pixels across the time series
 - the number of other invalid pixels (cloud, no data, saturated)

So my theory doesn't seem to hold. I recall seeing this issue before, but it was in areas with worse coverage and / or a lot of clouds. I'm not sure what else might explain it.

**Comment by valpesendorfer** [comment]
Thanks @lnicola ... would be interesting what caused it, I didn't find any error msgs in the logs.

Anyways, I've re-run the classification for this tile and now everything seems to be complete. So I'm closing the issue.

**Comment by lnicola** [comment]
I don't think it was an error, but the actual classifier output.

> Anyways, I've re-run the classification for this tile and now everything seems to be complete.

Did you re-run it for the whole site, or just on that specific tile? If it was for the whole site with the same parameters and input products, that's interesting.

**Comment by valpesendorfer** [comment]
> I don't think it was an error, but the actual classifier output.

But given that there's both reference and satellite data, how can an empty tiff file be a (correct) classifier output?

For the re-run, I've used the `--tile-filter` argument to restrict the classification, post-process and qualityflags steps to this specific tile. The strata, models, etc. was all from the previous run which was for the entire site.
The final quality metrics step was again done for the full site, just this time with the new tiff files for `35NRH` replacing the previous ones.

**Comment by lnicola** [comment]
> But given that there's both reference and satellite data, how can an empty tiff file be a (correct) classifier output?

The classifier is somewhat resilient to noise, so the classification result doesn't have to match the training data exactly (there might be outliers, for example).

> For the re-run, I've used the --tile-filter argument to restrict the classification, post-process and qualityflags steps to this specific tile. The strata, models, etc. was all from the previous run which was for the entire site.

The classification output should be (and usually is, as far as I know) deterministic, so.. that shouldn't have happened. I've no idea why, sorry.

**Comment by valpesendorfer** [comment]
That's why I think there must have been some kind of error. I'm quite familiar with Random Forest, but given there's a few reference data points, I wouldn't expect an output that has no sigle crop pixel. 

For now it's not a big issue, as far as this run is concerned, this seems to have been an isolated issue. But if it happens again, I would like to look a bit closer as to why that happens.

Thanks for now @lincola
