### ISSUE TITLE
How to run CropMaskFused.py from output of MAJA 3.3.0

### ISSUE THREAD

**Issue by mpotanin** [Sen2Agri/Sen2Agri-System#25]
Hi!
may I ask you if it's appropriate - what particular path (file or dir) from output of MAJA (3.3.0) should be put into "-input" parameter to run CropMaskFused.py script (run L4a proccessor in manual mode) ?

**Comment by lnicola** [comment]
Hi. Depending on which version of the system you have, you should be able to use the `_MTD_ALL.xml` file in the root of the product directory.

**Comment by mpotanin** [comment]
Thank you! It works!
