### ISSUE TITLE
Can`t visit the forum site

### ISSUE THREAD

**Issue by RhettButlerX** [Sen2Agri/Sen2Agri-System#30]
Hello, sorry to ask a qusetion that maybe is unrelated with this project.The forum site(https://forum.esa-sen2agri.org/) is disabled to visit since 2019/12/20.I asked some supporter(like scihub.support@copernicus.esa.int and eosupport@copernicus.esa.int ...) by email for this but I didnt get the solution yet.They suggeted me to contact the site managers but I can`t find the contact at the homepage or other sites.If anyone knows how to contact the forum-site managers, tell me please.
Thanks a lot.
![image](https://user-images.githubusercontent.com/20549449/71704893-cf951180-2e17-11ea-89f4-80d67e74f038.png)
![image](https://user-images.githubusercontent.com/20549449/71704968-184cca80-2e18-11ea-91da-0aa4cb819a95.png)

**Comment by lnicola** [comment]
We'll look into it, thanks for the report.

**Comment by RhettButlerX** [comment]
The site can be visited now, so I close this issue.Thanks.
